version: '3.8'
services:
  frontend:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./frontend:/usr/share/nginx/html

  backend:
    image: node:14
    working_dir: /app
    environment:
      - DB_URL=mongodb://db:27017/blog
    volumes:
      - ./backend:/app
    command: npm start
    depends_on:
      - db

  db:
    image: mongo:latest
    ports:
      - 27017:27017
