apiVersion: v1
kind: Pod
metadata:
  name: kafka-consumer
spec:
  containers:
  - name: kafka-consumer
    image: confluentinc/cp-kafka:latest
    command: ["/bin/sh", "-c"]
    args:
    - >
      sleep 20;  # Dê um tempo para o produtor produzir a mensagem
      kafka-console-consumer --bootstrap-server kafka:9092 --topic aula6 --from-beginning --timeout-ms 3000;

