apiVersion: v1
kind: Pod
metadata:
  name: kafka-producer
spec:
  containers:
  - name: kafka-producer
    image: confluentinc/cp-kafka:latest
    command: ["/bin/sh", "-c"]
    args:
    - >
      kafka-topics --create --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1 --topic aula6;
      echo "aula final parabens" | kafka-console-producer --broker-list kafka:9092 --topic aula6;
      sleep 10;

